/* eslint-disable */

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router.
// You should NOT make changes to this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createRoute } from '@tanstack/react-router'
import { Route as rootRoute } from './routes/__root.js'

// Import route modules
import { Route as IndexFileRoute } from './routes/index.js'
import { Route as SessionsFileRoute } from './routes/sessions.js'
import { Route as SettingsFileRoute } from './routes/settings.js'
import { Route as FlowsFileRoute } from './routes/flows.js'
import { Route as PromptsFileRoute } from './routes/prompts.js'

// Re-create routes with proper parent wiring and explicit paths
const IndexRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/',
  component: IndexFileRoute.options?.component,
})

const SessionsRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/sessions',
  component: SessionsFileRoute.options?.component,
})

const SettingsRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/settings',
  component: SettingsFileRoute.options?.component,
})

const FlowsRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/flows',
  component: FlowsFileRoute.options?.component,
})

const PromptsRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/prompts',
  component: PromptsFileRoute.options?.component,
})

// Build the route tree
export const routeTree = rootRoute.addChildren([
  IndexRoute,
  SessionsRoute,
  SettingsRoute,
  FlowsRoute,
  PromptsRoute,
])

// Type augmentation for createFileRoute path validation
declare module '@tanstack/router-core' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexFileRoute
      parentRoute: typeof rootRoute
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsFileRoute
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsFileRoute
      parentRoute: typeof rootRoute
    }
    '/flows': {
      id: '/flows'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof FlowsFileRoute
      parentRoute: typeof rootRoute
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsFileRoute
      parentRoute: typeof rootRoute
    }
  }
}
